services:
  - type: web
    name: kyp-backend
    runtime: node
    rootDir: Backend
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: MONAD_TESTNET_RPC
        sync: false
      - key: MONAD_MAINNET_RPC
        value: https://rpc.monad.xyz
      - key: VERIFIER_PRIVATE_KEY
        sync: false
      - key: KYP_CONTRACT_ADDRESS
        sync: false
      - key: KYP_CONTRACT_ADDRESS_MAINNET
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_PATH
        value: ./serviceaccount.json
      - key: FIREBASE_DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
